site_name: SMARTNav Dataset

use_directory_urls: false

nav:
  - Home: index.md
  - Practical Guide to SLAM: 
    - Introduction: introduction.md
    - Sensor Selection for SLAM: sensors.md
    - Calibtation of Sensors: calibration.md
    - Deployment of SLAM Algorithms: deployment.md
    - Interpretation of SLAM Results: interpretation.md

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  logo: images/SMART-RG-White-transparent.png

  palette:
    scheme: default     
    primary: teal        

extra_css:
  - css/custom.css
