site_name: SMARTNav Dataset
nav:
  - Home: index.md
  - Evaluation: eval.md
  - Examples: examples.md

theme:
  name: material
  logo: images/SMART-RG-White-transparent.png

  palette:
    scheme: default     
    primary: teal        

extra_css:
  - css/custom.css
